#!/usr/bin/env python
import json
import urllib.request
import sys

def version(package_name):
  url = "https://pypi.org/pypi/%s/json" % (package_name,)
  data = json.load(urllib.request.urlopen(url))
  version = data["info"]["version"]
  return version

if __name__ == "__main__":
  argv = sys.argv
  if len(argv) != 2:
    print("Usage: %s pkg_name" % argv[0])
    sys.exit(1)

  print(version(argv[1]))
